[pytest]
markers =
    smoke: Run basic smoke test cases like app launch
    signup_smoke: Run smoke tests related to signup functionality
    login_smoke: Run smoke tests related to login functionality
    profile_smoke: Run smoke tests related to profile functionality
    slider_smoke: Run smoke tests related to slider functionality
    home_smoke: Run smoke tests related to home functionality
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s